routes/dashboard.py
from flask import (
    Blueprint,
    request,
    redirect,
    url_for,
    make_response,
    jsonify,
    render_template,
)
from flask_login import login_user, current_user, login_required, LoginManager
from werkzeug.security import check_password_hash
from models.user import User
from main import db, csrf
from routes.auth import token_required


bp = Blueprint("dashboard", __name__)

@bp.route("/dashboard")
@token_required
def dashboard():
    return render_template("dashboard.html")

routes/index.py
from flask import (
    Blueprint,
    request,
    redirect,
    url_for,
    make_response,
    jsonify,
    render_template,
    Response,
    current_app,
    session,
)
from flask_babel import _
from flask_login import login_user, current_user
from werkzeug.security import check_password_hash
from models.user import User
from main import db, csrf

bp = Blueprint("index", __name__)


@csrf.exempt
@bp.route("/")
def home():
    if current_user.is_authenticated:
        return redirect(url_for("dashboard.dashboard"))
    return render_template("index.html")


@bp.route('/set_language/<language>', methods=['POST'])
def set_language(language):
    session['lang'] = language
    next_page = request.referrer or url_for('index.home')
    return redirect(next_page)

@bp.route('/static/css/custom-colors.css')
def customcss():
    customfg = "#1f2936"
    customfg2 = "#5e00d1"
    custombg = " radial-gradient(circle, #8b3cff, #4f26e5);"
    custombutton = "#334155"
    textcolor = "#ffffff"
    customfont = "Brush Script MT,cursive"
    css = f"""
    :root {{
        --customfg: {customfg};
        --customfg2: {customfg2};
        --custombg: {custombg};
        --custombutton: {custombutton};
        --textcolor: {textcolor};
        --customfont: {customfont};
    }}
    .custombg {{
        background: var(--custombg);
    }}
    .customfg {{
        background-color: var(--customfg);
    }}
    .customfg2 {{
        background-color: var(--customfg2);
    }}
    .custombutton {{
        background-color: var(--custombutton);
    }}
    .customtext {{
        color: var(--textcolor);
        font-family: var(--customfont);
    }}
    """
    return Response(css, mimetype='text/css')

templates/base.html
<!doctype html>
<html lang="pt" data-theme="dark">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="{{url_for('static', filename='js/jquery-3.7.1.min.js')}}"></script>
    <link
      rel="stylesheet"
      media="screen"
      href="{{url_for('static', filename='css/tailwind.css')}}"
    />
    <link
      rel="shortcut icon"
      href="{{ url_for('static', filename='icon/favicon.ico') }}"
    />
    <link rel="stylesheet" media="screen" href="static/css/custom-colors.css" />
    <link
      rel="stylesheet"
      media="screen"
      href="{{url_for('static', filename='css/fontawesome.css')}}"
    />
    <link
      rel="stylesheet"
      media="screen"
      href="{{url_for('static', filename='css/solid.css')}}"
    />
    <title>{% block title %} {% endblock %}</title>
  </head>

  {% block content %} {% endblock %}
</html>

templates/dashboard.html
{% extends 'base.html' %} {% block content %}
<title>{% block title %}Dashboard{% endblock %}</title>
<link rel="stylesheet" media="screen" href="{{url_for('static',filename='css/dashboard.css')}}" />
<script src="{{url_for('static',filename='js/dashboard.js')}}"></script>
<body class="items-center justify-center min-h-screen custombg">
  <!-- INFO: Navbar -->
  <nav class="customfg2 p-4 flex justify-between items-center">
    <div class="flex text-white text-lg custom-text">
      <img src="{{ url_for('static', filename='icon/icon.png') }}" class="w-8 mr-2" />
      Piggyzilla
    </div>
    <button class="text-white custombutton px-3 py-1 rounded-sm logoutbutton" id="logout">Logout</button>
  </nav>

  <!-- INFO: Sidebar & Main Content -->
  <div class="flex flex-col md:flex-row h-screen">
    <!-- INFO: Sidebar -->
    <aside class="customfg text-white w-full md:w-64 p-4 md:flex md:flex-col">
      <div class="hidden panel md:block">
        <ul>
          <li class="mb-4" id="dash">
            <a href="#" class="hover:bg-blue-800 customfg2 block p-2 rounded-sm">{{ _('Dashboard')}}</a>
          </li>

          <li class="mb-4" id="transactions">
            <a href="#" class="hover:bg-amber-200 customfg2 block p-2 rounded-sm">{{ _('Transactions') }}</a>
          </li>
          <li class="mb-4" id="income">
            <a href="#" class="hover:bg-blue-800 customfg2 block p-2 rounded-sm">{{ _('Income') }}</a>
          </li>
          <li class="mb-4" id="expense">
            <a href="#" class="hover:bg-blue-80
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block title %} Login {% endblock %}
{% block content %}
<body class="flex items-center justify-center min-h-screen custombg">


    <div class="fixed top-4 right-4 flex items-center space-x-2 z-10">
        <span class="customtext">PT</span>
        <div class="relative inline-block w-10 align-middle select-none">
            <form action="{{ url_for('index.set_language', language='en' if session.get('lang') == 'pt' else 'pt') }}" method="post">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <input type="checkbox" name="language" value="toggle" id="toggle" class="hidden" {{ 'checked' if session.get('lang') == 'en' else '' }} onchange="this.form.submit()">
                <label for="toggle" class="block overflow-hidden h-4 rounded-full bg-purple-300 cursor-pointer">
                    <span class="block w-4 h-4 bg-white rounded-full shadow-sm transform transition-transform duration-300 ease-in-out {{ 'translate-x-4' if session.get('lang') == 'en' else 'translate-x-0' }}"></span>
                </label>
            </form>
        </div>
        <span class="customtext">EN</span>
    </div>

    <div class="customfg bg-opacity-85 text-center text-white p-8 rounded-lg shadow-lg w-full max-w-md mt-12">
        <div class="flex flex-col items-center mb-6">
            <img src="{{ url_for('static', filename='icon/icon.png') }}" class="w-32 mb-4">
            <h2 class="text-2xl font-bold customtext">Piggyzilla</h2>
        </div>

        <form method="POST" id="loginForm"><form method="POST" action="#" id="loginForm">

            <div class="mb-4 text-left">
                <label for="username" class="block text-sm font-medium">{{ _('Username') }}</label>
                <input type="text" name="username" id="username" required
                       class="mt-1 block w-full text-center customtext rounded-sm border-gray-300 bg-gray-400 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 text-lg sm:text-sm min-h-8">
            </div>
            <div class="mb-6 text-left">
                <label for="password" class="block text-sm font-medium">{{ _('Password') }}</label>
                <input type="password" name="password" id="password" required
                       class="mt-1 block w-full text-center customtext rounded-sm border-gray-300 shadow-sm bg-gray-400 focus:border-indigo-500 focus:ring-indigo-500 text-lg sm:text-sm min-h-8">
            </div>
            <div class="flex items-center mb-4">
                <input id="remember" type="checkbox" name="remember" class="h-4 w-4 text-indigo-600 focus:ring-indigo-500 border-gray-300 rounded">
                <label for="remember" class="ml-2 block text-sm text-gray-100">
                    {{ _('Keep me logged in') }}
                </label>
            </div>
            <button type="submit"
                    class="w-full py-2 px-4 bg-indigo-600 customtext text-white rounded-md hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2">
                {{ _('Login') }}
            </button>
        </form>

        <div id="loginmessage" class="text-red-500 mt-4" style="display:none;"></div>
    </div>
    <script>
        $(document).ready(function() {
            var login_error="{{ _('Login or password are incorrect')}}"
            var process_error="{{ _('Error processing request')}}"
           
            $("#loginForm").on("submit", function(event) {
                event.preventDefault();

                $.ajax({
                    type: "POST",
                    url: "{{ url_for('auth.auth') }}",
                    data: $(this).serialize(),
                    success: function(response) {
                        if (response.success) {
                            window.location.href = "{{ url_for('index.home') }}";
                        } else {
                            $("#loginmessage").text(login_error).show();
                            setTimeout(function() {
                                $("#loginmessage").fadeOut();
                            }, 5000);
                        }
                    },
                    error: function() {
                        $("#loginmessage").text("{{ _("Error processing request") }}").show();
                        setTimeout(function() {
                            $("#loginmessage").fadeOut();
                        }, 3000);
                    }
                });
            });
        });
    </script>
</body>
{% endblock %}